SmartThingsCommunity/smartthings-core-sdk

- package.json
- src/endpoint/installedapps.ts
Default the `client.installedApps.delete()` function to use the configured installedAppId if present. Calling this method from API Access apps is a common use-case, and is required for backward compatibility with the SmartApp SDK
> Default installedApp.delete() to configured ISA ID

- package-lock.json
- package.json
- src/signature.ts
Missing or invalid auth header should simply fail auth rather than throw an exception
> fix: Catch missing/corrupted header exception in signature auth test

- package-lock.json
- src/signature.ts
Unit test was failing. Probably induced by the upgrade of one of the packages.
> Make logger optional in signature verifier

- package-lock.json
- package.json
- src/endpoint/devices.ts
- test/unit/devices.test.ts
Implementation already handled lack of args, but declaration of sendCommands didn't makes args optional.
> fix Correctly made args field optional in sendCommands

- package-lock.json
- package.json
- src/endpoint/apps.ts
- test/unit/data/apps/post_apps_requireConfirmation=false&signatureType=APP_RSA.ts
Fixed bug where signatureType was properly set to ST_PADLOCK but requireConfirmation flag was set improperly. Note that these query params are not being included in the API arguments because they are temporary.
> fix Corrected app create confirmation option

- package-lock.json
- package.json
- src/endpoint/installedapps.ts
Changed the properties of the various SmartApp config classes to not be optional. These values are always set in device config API responses. Their being optional creates a need for unnecessary checks in typescript clients.
> fix Corrected DeviceConfig type defs

- src/endpoint/schema.ts
- test/unit/data/presentation/presentation.ts
- fix misspelling of `SchemaCreateResponse`
- fix failing tests due to type changes in previous PR
> fix: correct spelling of SchemaCreateResponse

- package-lock.json
- package.json
- src/endpoint/presentation.ts
Corrected problem where presentations.getPresentation() did not have the correct arguments, namely `deviceId`, `mnmn`, and `vid`.
> fix Corrected get device presentation

- package-lock.json
- package.json
- src/endpoint/devices.ts
- src/endpoint/presentation.ts
Added `devices.getPresentation(deviceId)` method to get the presentation of a device and `presentation.getPresentation(vid, [mnmn])` to get presentation for a vid and mnmn.
> fix Separate device presentation methods

- src/endpoint/capabilities.ts
- test/unit/capabilities.test.ts
* add ability to pass arbitrary HTTP params to the CapabilitiesEndpoint create method
> feat: allow CapabilityCreate to accept params

- src/endpoint/capabilities.ts
Added additional properties found in capability schemas while making CLI enhancements:
`properties?: { [name: string]: CapabilityJSONSchema }`
[nested properties](https://github.com/SmartThingsCommunity/SmartThingsCapabilities/blob/master/capabilities/web-rtc.src/webrtc.yml#L34-L44)
`items?: CapabilityJSONSchema | [CapabilityJSONSchema]`
[items as a schema object](https://github.com/SmartThingsCommunity/SmartThingsCapabilities/blob/master/capabilities/web-rtc.src/webrtc.yml#L12-L13)
[items as an array of schema objects](https://github.com/SmartThingsCommunity/SmartThingsCapabilities/blob/master/capabilities/thermostat.src/thermostat.yml#L17-L19)
`title?: string`
[title of type](https://github.com/SmartThingsCommunity/SmartThingsCapabilities/blob/master/capabilities/thermostat.src/thermosta …
> fix Added missing capability schema properties

- package-lock.json
- package.json
- src/endpoint/devices.ts
Turns out the discrepancies between the API docs and values actually returned from the API have been corrected, so this ticket became just a matter of updating the TypeScript type definitions to match the API docs.
> fix Updated device type definitions

- .eslintrc.js
- src/endpoint-client.ts
- src/endpoint.ts
- src/endpoint/apps.ts
- src/endpoint/capabilities.ts
- src/endpoint/deviceprofiles.ts
- src/endpoint/devices.ts
- src/endpoint/installedapps.ts
- src/endpoint/locations.ts
- src/endpoint/modes.ts
- src/endpoint/notifications.ts
- src/endpoint/presentation.ts
- src/endpoint/rooms.ts
- src/endpoint/rules.ts
- src/endpoint/scenes.ts
- src/endpoint/schedules.ts
- src/endpoint/schema.ts
- src/endpoint/services.ts
- src/endpoint/subscriptions.ts
- test/unit/endpoint-client.test.ts
Removed `default` from export for `EndpointClient` class and fixed imports so it gets exported for external use.
> fix: export EndpointClient class normally so it can be used directly outside SDK

- src/endpoint-client.ts
- test/unit/endpoint-client.test.ts
added support for an "options" parameter to the basic request method in the `EndpointClient` class which includes:
* `headerOverrides`: header values to override the defaults
* `dryRun`: boolean to skip actual request (but still logs)...not sure if I should have left this in but it might be helpful in the future
* `dryRunReturnValue`: a value to return in `dryRun` mode if just throwing an exception isn't gonna work for your testing
> feat: support header overrides in EndpointClient

- .editorconfig
- .github/workflows/cd.yml
* update our workflow to set env variables [detailed here](https://github.com/semantic-release/git#git-authentication)
This will allow us to have branch protections in place while also automating these chore commits from releases.
> chore: configure semantic-release to use PI bot

- .github/workflows/cd.yml
* include [workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) events on master branch
> chore: add ability to manually run release

- src/endpoint/subscriptions.ts
- If `options.stateChangeOnly` is `false`,  `true` will be set to `stateChangeOnly` field by ternary operator.
- Changed to check `options.stateChangeOnly` is `undefined` or not.
> fix: can be set `stateChangeOnly` false

- src/endpoint/presentation.ts
- test/unit/data/presentation/presentation.ts
Updated device configuration type def to include the `patch` property for overriding capability presentation values.
https://smartthings.developer.samsung.com/docs/api-ref/st-api.html#operation/createDeviceConfiguration
> feat: Add patch property to device configs

- src/endpoint/presentation.ts
- test/unit/data/presentation/presentation.ts
- test/unit/presentation.test.ts
Changed `vid` to `presentationId` and `mnmn` to `manufacturerName`.
The current API accepts either vid/mnmn or presentationId/manufacturerName and returns both in the response. However, at some point vid and mnmn will be removed from the response and no longer accepted as parameters. For that reason I think this update should be considered a breaking change. It won't actually break anything for JavaScript clients (until the API removes mnmn and vid), but it will result in an error for TypeScript clients referencing those field, as it should, since they are
eventually going away.
> BREAKING CHANGE: Change from vid to presentationId

- src/endpoint/subscriptions.ts
- test/unit/data/subscriptions/post_installedapps_subscriptions.ts
- test/unit/subscriptions.test.ts
Fix to issue #63 
Also removes `subscriptions.update()` function since it was included in error. There is no corresponding PUT method for subscriptions. 
Not considered a breaking change since this function, if used, would not have previously worked.
> fix: Use POST rather than PUT for subscriptions.create

- README.md
Updated the line numbers in the hrefs from the README file to consistently point to the section of code that defines the methods of each endpoint.
> chore: Updated code link line numbers in README.md

- src/endpoint/devices.ts
- test/unit/data/devices/put_devices.ts
- test/unit/data/devices/put_devices_profile.ts
- test/unit/devices.test.ts
Added new devices `updateProfile` method that allows the device profile ID of a device to be changed. This method can only be called with an installedApp token that includes the `i:deviceprofiles` scope, and only for devices created by that installedApp.
> feat: Added devices.updateProfile method

- .eslintrc.js
- global.d.ts
- package-lock.json
- package.json
- src/endpoint/devices.ts
- tsconfig-test.json
* ran `npm audit fix`
* enabled `@typescript-eslint/no-floating-promises` rule, updating necessary configuration to allow this
* don't validate .eslint config file itself...this is apparently  not normal and was making it difficult to enable the configuration necessary to enable this rule
* fixed one error found by rule; this changes the return type of a method from `void` to `Promise<void>`--I'm not sure if this would be a breaking change or not
* fixed path for source files in tsconfig.json which exposed a warning in one of the files related to importing a module (http-signature) which has not TypeScript definitions
* added global.d.ts file to get TypeScript to ignore missing definitions for http-signature
> fix: enable no-floating-promises lint rule and fix issue found

- src/endpoint/presentation.ts
- test/unit/data/presentation/device-config.ts
- test/unit/data/presentation/presentation.ts
- test/unit/presentation.test.ts
Added missing manufacturerName parameter to the presentation endpoint's `get` method. Also added unit tests for the `getPresentation` method.
> fix: Added missing second parameter to presentation.get()

- package.json
- src/endpoint-client.ts
- src/endpoint/devices.ts
- test/unit/data/devices/get_devices.ts
- test/unit/data/devices/get_devices_385931b6-0121-4848-bcc8-54cb76436de1.ts
- test/unit/data/devices/get_devices_health_locationId=95efee9b-6073-4871-b5ba-de6642187293.ts
- test/unit/data/devices/get_devices_page_1_max_200.ts
- test/unit/data/devices/get_devices_status_locationId=95efee9b-6073-4871-b5ba-de6642187293.ts
- test/unit/data/devices/list_devices_by_isa.ts
- test/unit/data/devices/list_devices_by_type.ts
- test/unit/devices.test.ts
Added the includeHealth and includeStatus options for the devices list and get methods. These are currently supported in the proper API version and save a lot of API calls in many common scenarios. Also updated the client get, put, post, etc. methods to accept headers, rather than forcing the endpoint to have to drop back to _request_.
> feat: Added device includeHealth and includeStatus options

- src/endpoint-client.ts
- src/endpoint/deviceprofiles.ts
- src/endpoint/devices.ts
* Added type info for new device preferences in-line inside device preferences.
* Removed extraneous `owner` field.
* Added a little more trace-level debug when making axios requests.
> feat: add types for preferences in device profiles types

- src/endpoint/schema.ts
- test/unit/data/schema/post.ts
- test/unit/schema.test.ts
Added endpoint to regenerate OAuth clientId and clientSecret for ST Schema apps
> feat: Added endpoint to regenerate schema oauth credentials

- src/endpoint/organizations.ts
- src/st-client.ts
- test/unit/st-client.test.ts
Added method to clone a client with a different set of headers. Necessary so that one CLI command can call methods
on behalf of different organizations
> feat: Added method for cloning client with different headers

- src/endpoint-client.ts
- src/endpoint/deviceprofiles.ts
- src/rest-client.ts
- test/unit/endpoint-client.test.ts
* added a `warningLogger` config option that the CLI can use to log warning messages
* updated unit tests including adding tests for a couple of methods that were previously not unit-tested
Axios combines multiple headers into a single comma-separated string so I put code here to split them and parse the fields of each warning. If, for any reason, the string cannot be parsed it will simply be passed to the warning logger. I did this rather than throwing an exception because a badly formatted warning message or a bug in our parsing to break the CLI.
> feat: add support for logging RFC 2068 warning headers

- src/endpoint/drivers.ts
- test/unit/drivers.test.ts
* Added support for new endpoint listing drivers in default channel (a channel users have access to without subscribing to it).
> feat: add support for listing drivers in default channel

- .eslintrc.js
- src/endpoint/capabilities.ts
- src/endpoint/rules.ts
- test/unit/rules.test.ts
BREAKING CHANGE: Updated rules model objects have been significantly updated.
* updated rules model objects to match current API
* renamed some very generically named objects
* more idiomatic TypeScript "enums"
> fix(rules): update rules model objects to match current API

- src/endpoint/capabilities.ts
Fixed the type of `items` for the `CapabilityJSONSchema` interface to allow arrays of any size per the spec.
> fix: correct type of JSON schema v4 items property

- .vscode/settings.json
- src/endpoint/hubdevices.ts
- test/unit/hubdevices.test.ts
added support for including `forceUpdate` parameter when switching drivers
This is needed by the [CLI PR #427](https://github.com/SmartThingsCommunity/smartthings-cli/pull/427).
> fix: add support for including forceUpdate parameter when switching drivers

- src/endpoint/subscriptions.ts
Change language in the `subscriptions.delete()` method to properly state that deletion of individual subscriptions requires a subscription UUID.
> chore: clarify language about deleting subscriptions

- .changeset/flat-deers-relate.md
- src/endpoint/drivers.ts
- test/unit/drivers.test.ts
Corrected the type returned by the edge drivers `listDefault()` command. It's the complete driver definition, not just the summary.
> fix: corrected type returned by default drivers command

- .changeset/five-sloths-cheer.md
- package-lock.json
- package.json
Revert axios to CommonJS-only version. The newer combined ESM/CommonJS version confuses the `pkg` tool used to build the CLI binary.
> fix: revert axios to CommonJS-only version

- .changeset/thick-students-tan.md
- src/endpoint/invites-schemaApp.ts
- test/unit/invites-schemaApp.test.ts
* added `acceptances` field
* removed `getAcceptanceStatus` and `accept` and related code
> fix: minor st-schema invite updates

- .changeset/friendly-turtles-kneel.md
- src/authenticator.ts
- src/endpoint-client.ts
- test/unit/authenticator.test.ts
- test/unit/endpoint-client.test.ts
Updated core SDK to decouple it from the axios version it uses. Dependents are now free to use whatever version of axios (or none if another request module is desired).
The old `Authorization` interface had two methods, `authenticate` and `authenticateGeneric`. The `authenticate` method was tied to axios so it was removed. The `authenticateGeneric` method was then renamed to `authenticate` and its return type was changed slightly to make it easier to use. (It now returns headers which can be folded into the user's request rather than simply the token.)
The code that used the `authenticate` method was updated accordingly.
Unit tests were also updated as well. A couple of unit tests were moved and a few unrelated new unit tests were added to more fully cover `endpoint-client.ts` as well. …
> fix: decouple axios version from core SDK

- .changeset/shiny-swans-flash.md
- README.md
- package-lock.json
- package.json
- src/endpoint-client.ts
- test/unit/endpoint-client.test.ts
- test/unit/helpers/utils.ts
While the documentation for axios suggests that using a simple function for `paramsSerializer` should work with 0.28, [it does not](https://github.com/axios/axios/issues/6341). Since npm considers 0.28 and 0.28.1 to be compatible, users or the core SDK who also include axios 0.28.1 are getting errors. This updates the core SDK to 0.28.1. This will break users who are using anything less than 0.28.1 (hence the note in the README).
> fix: workaround axios bug

- .changeset/lemon-bobcats-tap.md
- src/endpoint/schema.ts
Added support for requesting Schema Apps by organization.
Related CLI pull request:
https://github.com/SmartThingsCommunity/smartthings-cli/pull/612
> feat: add support for listing Schema apps by organization

- .changeset/good-houses-give.md
- src/endpoint/invites-schemaApp.ts
- src/endpoint/schema.ts
- test/unit/invites-schemaApp.test.ts
* implement a workaround for the schema invites endpoint throwing a 403 for schema connectors without an organization id
* some minor comment updates
> fix: implement workaround for schema invitations endpoint returning 403

- .changeset/forty-monkeys-sneeze.md
- src/endpoint/devices.ts
Added missing export for `AttributeState` interface.
> fix: add missing export on AttributeState

- .changeset/short-waves-cough.md
- .github/workflows/ci-cd.yaml
- package-lock.json
- package.json
* updated build to use Node 22
* updated targets to 18, 20, and 22
* ran `npm audit fix`
> fix: remove node 14 and 16; add 20 and 22
