- package-lock.json
- package.json
- src/endpoint/devices.ts
- test/unit/data/devices/post_devices_385931b6-0121-4848-bcc8-54cb76436de1_events.ts
- test/unit/devices.test.ts
Event list property name was incorrect
> fix: Corrected error in device.createEvents()

- package.json
- src/endpoint/devices.ts
- test/unit/data/devices/post_devices.ts
- test/unit/data/devices/post_devices_2.ts
- test/unit/devices.test.ts
The `app` element was incorrectly nested.
> fix: Corrected error in device.create()

- src/endpoint/apps.ts
- src/endpoint/capabilities.ts
- src/endpoint/deviceprofiles.ts
- src/endpoint/installedapps.ts
- src/endpoint/notifications.ts
- src/endpoint/rules.ts
- src/endpoint/schedules.ts
- src/endpoint/schema.ts
- src/endpoint/subscriptions.ts
- src/signature.ts
- test/unit/capabilities.test.ts
- test/unit/data/capabilities/capability1.ts
- test/unit/data/capabilities/create1.ts
- Added support for custom capabilities to the SDK.
- Made arrays consistently use `[]` format.
> add custom capabilities presentation methods

- package-lock.json
- package.json
- src/endpoint/installedapps.ts
- test/unit/data/installedapps/get_installedapps_installedAppStatus=AUTHORIZED.ts
- test/unit/data/installedapps/get_installedapps_installedAppType=WEBHOOK_SMART_APP.ts
- test/unit/installedapps.test.ts
Fixed copy and past errors in installed apps list() method and corrected some types used by it
> Fixed bugs in installedApps endpoint

- src/endpoint/presentation.ts
- test/unit/data/presentation/presentationForGet.ts
- test/unit/presentation.test.ts
- fix property case on iconUrl property name
- fix lint error
> fix property case on iconUrl property name

- package.json
- src/endpoint/apps.ts
Also bumped version for deployment
> fix Adding missing ApiOnly property to app App interface

- package-lock.json
- package.json
- src/endpoint/subscriptions.ts
Duplicate "installedapps" in request path.
> fix Corrected bug in device health subscriptions

- .eslintrc.js
- src/endpoint/capabilities.ts
Updated types to match changes made to API.
> update types to match current api

- README.md
Links now point to the Wiki pages
> Update readme to point the links

- .releaserc.yml
- package-lock.json
- package.json
- include `@semantic-release/git` plugin to automatically bump release version in `package.json` and `package-lock.json`
> chore: include semantic-release git plugin

- package-lock.json
- package.json
Removed "version" script from package.json that was randomly running "npm format".
(Also ran 'npm audit fix' which fixed a couple dependencies in package-lock.json but was unable to fix a couple others.)
> bug: remove bad version script from package.json

- src/endpoint/devices.ts
Updated list of types to match current API docs.
> fix: bring device types in-line with API docs

- package-lock.json
- package.json
- src/endpoint/devices.ts
- src/endpoint/rooms.ts
- test/unit/data/devices/list_devices_by_type.ts
- test/unit/devices.test.ts
Added support for adding extra HTTP parameters when using devices list command.
> feat: support searching by device integration type when listing devices

- README.md
BREAKING CHANGE: previous commit to change vid to presentationId is a breaking change
> feat: Force a release and updated README

- package-lock.json
- src/logger.ts
* ran `npm audit fix`
* removed unused and ambiguous `log` method that didn't specify a level
> fix: remove ambiguous log method

- src/endpoint/devices.ts
- test/unit/data/devices/list_devices_by_isa.ts
- test/unit/devices.test.ts
Fix to one portion of issue #70
> fix: Accept installedAppId in devices list query

- src/endpoint/rules.ts
Updated rule type definitions to reflect newly added features.
> feat: Added new conditions and actions

- src/endpoint/capabilities.ts
Added documentation on restrictions for capability attribute and command names.
> docs: add documentation for capability attribute and command names

- src/endpoint/installedapps.ts
- test/unit/data/installedapps/get_installedapps.ts
- test/unit/data/installedapps/get_installedapps_40593b6d-e062-436a-b17e-86ea3f1d979c.ts
Attribute is currently being returned from the public API
> feat: Added new restrictionTier attribute to installedapps

- src/endpoint/capabilities.ts
- test/unit/capabilities.test.ts
* added missing `createTranslations` and `updateTranslations` methods for capability translations
* fixed `upsertTranslations` to work as an upsert in code since the API doesn't work that way for capabilities
* updated unit tests
> fix: added missing capability translations methods

- src/endpoint/deviceprofiles.ts
- src/endpoint/devices.ts
- test/unit/data/devices/get_preferences.ts
- test/unit/devices.test.ts
Added `devices.getPreferences(deviceId) ` method to retrieve the preference values of a device.
> feat: Added method to retrieve device preference values

- package-lock.json
- package.json
* resolves dependabot alert for `highlight.js`
> chore: bump typedoc and peer deps

- .vscode/settings.json
- jest.config.js
- package.json
- src/endpoint/devicepreferences.ts
- src/index.ts
- src/st-client.ts
- test/unit/capabilities.test.ts
- test/unit/data/devicepreferences/get.ts
- test/unit/data/devicepreferences/post.ts
- test/unit/devicepreferences.test.ts
* added support for device preferences crud operations
* limit code coverage to the code being tested (ignoring tests)
> feat: add support for device preferences CRUD operations

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- prevent release job from running on forks
- cache npm modules
> build: update node versions

- src/endpoint/devices.ts
> fix: corrected childDevices type in Device model object

- src/endpoint/devicepreferences.ts
- test/unit/devicepreferences.test.ts
- list preference localizations
- update a preference localization for a locale
> feat(devicepreferences): expand i18n support

- .commitlintrc.yml
- .czrc
- .github/workflows/ci.yml
- .github/workflows/commitlint.yml
- .releaserc.yml
- .vscode/settings.json
- CHANGELOG.md
- CONTRIBUTING.md
- package-lock.json
- package.json
- make repo commitizen friendly
> ci: add commitlint action

- src/endpoint/devicepreferences.ts
- test/unit/devicepreferences.test.ts
> fix(devicepreferences): unwrap paged items in response

- src/endpoint/rules.ts
> fix(rules): correct IfAction 'else' property

- package-lock.json
- src/rest-client.ts
- src/st-client.ts
- test/unit/st-client.test.ts
> feat(SmartThingsClient): merge headers during clone

- package-lock.json
- package.json
- src/endpoint/schedules.ts
> perf: replace underscore with lodash modules

- src/endpoint/devices.ts
Updated device model objects to match current documentation.
> feat: update device models

- README.md
* added documentation for using a logger
> docs: add documentation passing a logger to the client

- .github/workflows/ci-cd.yaml
- .github/workflows/create-jira-issue.yaml
- package-lock.json
- package.json
- add missing component id to Jira issue action
- use github actions token instead of API token
> ci: drop support for Node 12

- .github/workflows/stale.yaml
> ci: set stale reason to not_planned

- .github/workflows/ci-cd.yaml
> chore: fix problem with release of protected branch

- .github/workflows/ci-cd.yaml
Use our own Github token rather than the one provided, for now.
> chore: use our own Github token for now

- .github/workflows/ci-cd.yaml
Add debug for semantic-release for now.
> chore: add debug to semantic-release run

- .github/workflows/ci-cd.yaml
> chore: use GH_TOKEN instead of GITHUB_TOKEN for release

- .github/workflows/ci-cd.yaml
Try without:
```
with:
persist-credentials: false
```
> chore: try without disabling persist-credentials

- .github/workflows/ci-cd.yaml
> chore: put back disabling persiting of credentials

- .github/workflows/ci-cd.yaml
> chore: turn of semantic-release debug

- .github/workflows/ci-cd.yaml
> chore: try release without 'needs: build'

- .github/workflows/ci-cd.yaml
> chore: put back needs build

- .github/workflows/ci-cd.yaml
> ci(release): remove persist-credentials option

- src/endpoint/devices.ts
- src/endpoint/virtualdevices.ts
Fixed a couple of minor issues with the virtual device fields.
> fix: update virtual device fields

- src/endpoint/virtualdevices.ts
> fix: added channelId to virtual device create requests

- src/endpoint/drivers.ts
- src/endpoint/schema.ts
* Added `partnerSTConnection` field to schema app object.
* Added `description` to drivers object.
> fix: add missing fields

- .github/workflows/ci-cd.yaml
- CONTRIBUTING.md
- README.md
Updated code for using `main` name for main branch.
> chore: use "main" for main branch

- .changeset/sharp-kangaroos-wash.md
add changeset for last commit that wasn't released
> build: add changeset for last commit that wasn't released

- package.json
add missing version npm script
> build: add missing version npm script

- .changeset/config.json
fix access for changeset release
> build: fix access for changeset release

- CONTRIBUTING.md
- README.md
- update links in documentation
- other minor corrections to documentation
> docs: update links in documentation

- .changeset/shiny-peas-develop.md
- src/endpoint/apps.ts
- src/endpoint/installedapps.ts
Fixed `apiOnly` in `AppRequest` to match what is really used.
> fix: minor fixes to app types

- src/endpoint/apps.ts
Put back accidentally removed `appType` field (moved into shared base class because this one is used everywhere).
> fix: put accidentally removed field back

- src/endpoint/hubdevices.ts
- test/unit/hubdevices.test.ts
Added endpoint for getting hub definition and characteristics
> feat: added endpoint for hub characteristics

- .changeset/early-donuts-drop.md
Changeset to deploy hub characteristics PR I just merged that was created before we were using changesets.
> feat: added hub characteristics endpoint

- .changeset/chilled-rivers-sell.md
- package-lock.json
- package.json
- src/endpoint-client.ts
- test/unit/endpoint-client.test.ts
- test/unit/helpers/utils.ts
* backed off axios version to latest non-ESM version (to support building the CLI which uses the pkg tool)
* backed off changes to code that were required for axios upgrade
> fix: support pkg builds again

- CONTRIBUTING.md
- package.json
- tsdoc.json
Replace `SmartThings, Inc.` with `Samsung Electronics Co., LTD.`
> docs: update copyright company name

- .changeset/curvy-pots-arrive.md
- package-lock.json
- package.json
* updated axios and qs dependencies
> chore: update axios and qs dependencies

- .changeset/beige-schools-end.md
- src/endpoint/invites-schemaApp.ts
Include `acceptLimit` field in ST Schema invitation creation.
> fix: include acceptLimit field in ST Schema invites

- .changeset/eight-poets-deliver.md
- src/endpoint/schema.ts
Added organizationId field to SchemaApp class
> feat: added organization ID to Schema apps

- .changeset/dirty-adults-rule.md
- package-lock.json
- package.json
- tsconfig.json
* updated axios version
* added "DOM" library needed by axios (found this fix buried in [axios issue #3219](https://github.com/axios/axios/issues/3219))
> chore: update axios to 0.28

- package.json
fix package.json with `npm pkg fix`
> fix: fix package.json with `npm pkg fix`

- .changeset/pink-bananas-glow.md
- src/endpoint/schema.ts
- test/unit/schema.test.ts
Added the ability to include an organization id when creating or updating schema apps.
> add ability to include organization with schema creation and update
